apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jetbrainsls-disk
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 4Gi
---
