image:
  name: crazymax/jetbrains-license-server
  registry: registry-1.docker.io
  tag: latest
dns:
  name: k8s.cs.calvin.edu
rollingUpdate:
  enabled: true
  maxSurge: "100%"
  maxUnavailable: "100%"
